language: php
php:
    - 7.2
services:
    - docker
before_install:
    - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
    - docker build -t dyndns .
    - mkdir /home/dyndns && cp tests/config.test.ini /home/dyndns && chown -R www-data /home/dyndns
    - docker run -d -p 127.0.0.1:80:80 -v /home/dyndns:/data --name dyndns dyndns
before_script:
  - phpenv config-rm xdebug.ini
script:
  - composer install
  - phpunit
after_failure:
  - docker logs dyndns